# Copyright 2026 Dimensional Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

"""G1 physical description, URDF frames, and sensor mounting."""

from __future__ import annotations

from dataclasses import dataclass
from functools import cached_property
from pathlib import Path

from dimos.msgs.geometry_msgs.Transform import Transform
from dimos.robot.urdf_loader import UrdfLoader
from dimos.utils.data import LfsPath

# generated by CMU's pathGenerator (autonomous_exploration_development_environment/local_planner);
# regenerate only for robots whose footprint differs notably from the g1
G1_LOCAL_PLANNER_PRECOMPUTED_PATHS = LfsPath("unitree_g1_local_planner_precomputed_paths")


@dataclass(frozen=True)
class G1Config:
    """Physical metadata used by G1 navigation and sensor blueprints."""

    name: str
    urdf_path: Path
    height_clearance: float
    width_clearance: float
    sensor_height: float

    @cached_property
    def urdf(self) -> UrdfLoader:
        return UrdfLoader(name=self.name, model_path=self.urdf_path)

    @property
    def static_transforms(self) -> dict[str, Transform]:
        return self.urdf.static_transforms


G1 = G1Config(
    name="unitree_g1",
    urdf_path=Path(__file__).parent / "g1.urdf",
    height_clearance=1.2,
    width_clearance=0.6,
    sensor_height=1.2,
)
