from numpy import float64
from numpy.typing import NDArray

from . import damiao as damiao

FloatArray = NDArray[float64]

class MotorSpec:
    def __init__(self, name: str, type: object, send_id: int, recv_id: int) -> None: ...

class MockCanBus:
    def __init__(self, name: str, fd: bool = False) -> None: ...
    @staticmethod
    def new_fd(name: str) -> object: ...

class SocketCanBus:
    def __init__(self, interface: str, fd: bool = False) -> None: ...

class ArmMotor:
    fault: int | None

class Arm:
    def __len__(self) -> int: ...
    def __getitem__(self, name: str) -> ArmMotor: ...
    def refresh(self) -> None: ...
    def positions(self) -> FloatArray: ...
    def velocities(self) -> FloatArray: ...
    def torques(self) -> FloatArray: ...
    def mit_control(self, cmds: FloatArray) -> None: ...

class RobotBuilder:
    def add_bus(self, name: str, transport: object, codec: object) -> RobotBuilder: ...
    def add_arm(self, name: str, *, bus: str, motors: list[object]) -> RobotBuilder: ...
    def build(self) -> Robot: ...

class Robot:
    @classmethod
    def builder(cls) -> RobotBuilder: ...
    @classmethod
    def from_config(cls, path: str) -> Robot: ...
    def __getitem__(self, name: str) -> Arm: ...
    def connect(self) -> None: ...
    def enable(self) -> None: ...
    def disable(self) -> None: ...
    def tick(self, per_bus_deadline_us: int) -> None: ...
